language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

env:
  - DJANGO="django>=1.11,<2.0"
  - DJANGO="django>=2.0,<2.1"
  - DJANGO="django>=2.1,<2.2"

before_install:
  - export DJANGO_SETTINGS_MODULE=demo.demo_classified.project.settings
  - export PYTHONPATH=$HOME/builds/inoks/django-classified
  - export PIP_USE_MIRRORS=true

install:
  - pip install $DJANGO --quiet
  - python setup.py install
  - pip install flake8
  - pip install coverage

before_script:
  - flake8  --ignore=E501,E122

script:
  - coverage run --source='.' quicktest.py django_classified

after_success:
  - coverage report --show-missing

matrix:
    exclude:
        - python: 2.7
          env: DJANGO="django>=2.0,<2.1"
        - python: 2.7
          env: DJANGO="django>=2.1,<2.2"
