language: python

python:
  - 2.7
  - 3.5
  - 3.6

env:
  - DJANGO="1.11"
  - DJANGO=">=2.0,<2.1"

before_install:
  - export DJANGO_SETTINGS_MODULE=project.settings
  - export PYTHONPATH=$HOME/builds/inoks/dcf
  - export PIP_USE_MIRRORS=true

install:
  - pip install django==$DJANGO --quiet

before_script:
  - flake8  --ignore=E501

script:
  - coverage run --source='./dcf' manage.py test

after_success:
  - coverage report --show-missing

matrix:
    exclude:
        - python: 2.7
          env: DJANGO_VERSION=">=2.0,<2.1"
